version: "3"
services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: WhatsInTheBox7
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - postgres